name: Build base images

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/builder.yml"
      - "Dockerfile"
      - "patches/**"
      - "requirements.txt"
      - "rootfs/**"
  release:
    types: ["published"]

env:
  REGISTRY_PREFIX: ghcr.io/${{ github.repository_owner }}
  BASE_IMAGE_REGISTRY_PREFIX: ghcr.io/${{ github.repository_owner }}
  ARCHITECTURES: '["armv7", "armhf"]'
  BUILD_TYPE: generic
  IMAGE_NAME: homeassistant-base

permissions:
  contents: read

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master
        with:
          type: ${{ env.BUILD_TYPE }}

      - name: Get build matrix
        id: matrix
        uses: edbordin/homeassistant-builder/actions/prepare-multi-arch-matrix@restore-armv7-armhf-builds
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}
          registry-prefix: ${{ env.REGISTRY_PREFIX }}

  build:
    name: Build ${{ matrix.arch }} base image
    needs: init
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Check if requirements or workflow has changed
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47
        if: github.event_name != 'release'
        id: wheels_deps_changed
        with:
          files: |
            requirements.txt
            .github/workflows/builder.yml

      - name: Build wheels cp314
        uses: home-assistant/wheels@2025.12.0
        if: github.event_name == 'release' || steps.wheels_deps_changed.outputs.any_changed == 'true'
        with:
          tag: musllinux_1_2
          abi: cp314
          arch: ${{ matrix.arch }}
          wheels-key: ${{ secrets.WHEELS_KEY }}
          apk: "mariadb-dev;postgresql-dev;libffi-dev"
          requirements: "requirements.txt"

      - name: Build base image
        uses: edbordin/homeassistant-builder/actions/build-image@restore-armv7-armhf-builds
        with:
          arch: ${{ matrix.arch }}
          build-args: |
            BUILD_FROM=${{ env.BASE_IMAGE_REGISTRY_PREFIX }}/base-python:3.14-alpine3.22
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.image }}
          image-tags: |
            ${{ needs.init.outputs.version }}
            latest
          platform: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          version: ${{ needs.init.outputs.version }}

  manifest:
    name: Publish multi-arch manifest
    needs: [init, build]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Publish multi-arch manifest
        uses: edbordin/homeassistant-builder/actions/publish-multi-arch-manifest@restore-armv7-armhf-builds
        with:
          architectures: ${{ env.ARCHITECTURES }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.IMAGE_NAME }}
          registry-prefix: ${{ env.REGISTRY_PREFIX }}
          image-tags: |
            ${{ needs.init.outputs.version }}
            latest
